# use the latest ubuntu environment (18.04) available on travis
dist: focal

language: go

go:
  - 1.15.x

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

notifications:
  email: false

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - go build                # ensure the program compiles
  - go test -v -race ./...  # Run all the tests with the race detector enabled
#  - go get -u golang.org/x/lint/golint; golint -set_exit_status ./...